import { useState, useEffect, useRef } from 'react';
import { useToast } from './Toast';

/**
 * GrokVideoGenerator — Modal component for generating videos via Grok Imagine API.
 *
 * Props:
 *   prompt      — The pre-filled prompt text
 *   promptName  — Display name of the prompt
 *   onClose     — Callback to close the modal
 *   isOpen      — Whether the modal is visible
 */
export default function GrokVideoGenerator({ prompt, promptName, onClose, isOpen }) {
  const toast = useToast();

  const [editablePrompt, setEditablePrompt] = useState(prompt || '');
  const [duration, setDuration] = useState('10');
  const [aspectRatio, setAspectRatio] = useState('9:16');
  const [resolution, setResolution] = useState('720p');
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [videoUrl, setVideoUrl] = useState(null);
  const [statusMessage, setStatusMessage] = useState('');
  const pollRef = useRef(null);
  const progressRef = useRef(null);

  // Sync prompt prop
  useEffect(() => {
    if (prompt) setEditablePrompt(prompt);
  }, [prompt]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
      if (progressRef.current) clearInterval(progressRef.current);
    };
  }, []);

  const handleGenerate = async () => {
    if (!editablePrompt.trim()) {
      toast.error('Please enter a prompt');
      return;
    }

    setIsGenerating(true);
    setProgress(0);
    setVideoUrl(null);
    setStatusMessage('Starting video generation...');
    toast.info(`Generating video — this may take 5-8 minutes`);

    // Simulate progress (5-8 minutes typical)
    progressRef.current = setInterval(() => {
      setProgress(prev => {
        if (prev >= 95) {
          clearInterval(progressRef.current);
          return 95;
        }
        return prev + 1.5;
      });
    }, 8000);

    try {
      // Start generation
      const genRes = await fetch('/api/grok/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: editablePrompt,
          duration: parseInt(duration),
          aspect_ratio: aspectRatio,
          resolution,
        }),
      });

      if (!genRes.ok) {
        const err = await genRes.json();
        throw new Error(err.error || 'Failed to start generation');
      }

      const { request_id } = await genRes.json();
      setStatusMessage('Video is being generated by Grok Imagine...');

      // Poll for status every 10 seconds, up to 10 minutes
      let attempts = 0;
      const maxAttempts = 60;

      pollRef.current = setInterval(async () => {
        attempts++;
        if (attempts > maxAttempts) {
          clearInterval(pollRef.current);
          clearInterval(progressRef.current);
          setIsGenerating(false);
          setStatusMessage('Generation timed out. Please try again.');
          toast.error('Video generation timed out');
          return;
        }

        try {
          const statusRes = await fetch(`/api/grok/status?request_id=${request_id}`);
          const statusData = await statusRes.json();

          if (statusData.status === 'done' && statusData.video_url) {
            clearInterval(pollRef.current);
            clearInterval(progressRef.current);
            setProgress(100);
            setVideoUrl(statusData.video_url);
            setIsGenerating(false);
            setStatusMessage('Video generated successfully!');
            toast.success('Video is ready!');
          } else if (statusData.status === 'expired' || statusData.error) {
            clearInterval(pollRef.current);
            clearInterval(progressRef.current);
            setIsGenerating(false);
            setStatusMessage('Generation failed. Please try again.');
            toast.error('Video generation failed');
          } else {
            setStatusMessage(`Generating... (${Math.round(progress)}%)`);
          }
        } catch {
          // Silently retry on network errors
        }
      }, 10000);
    } catch (error) {
      clearInterval(progressRef.current);
      setIsGenerating(false);
      setStatusMessage('');
      toast.error(error.message || 'Generation failed');
    }
  };

  const handleDownload = async () => {
    if (!videoUrl) return;
    try {
      const response = await fetch(videoUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const safeName = (promptName || 'video').replace(/[^a-zA-Z0-9]/g, '_');
      a.download = `DigiBloom_${safeName}.mp4`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success('Download started');
    } catch {
      toast.error('Download failed');
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
      <div className="w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-2xl border border-[#D4AF37]/20 bg-[#0a0a14] shadow-2xl">
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between px-5 py-4 border-b border-white/[0.06] bg-[#0a0a14]">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-[#D4AF37]/15 flex items-center justify-center">
              <svg className="w-4 h-4 text-[#D4AF37]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
            </div>
            <div>
              <h2 className="text-sm font-display font-bold text-white">Generate Video</h2>
              <p className="text-[10px] text-white/30">Powered by Grok Imagine</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors"
          >
            <svg className="w-4 h-4 text-white/50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="p-5 space-y-4">
          {/* Prompt Name */}
          {promptName && (
            <div className="px-3 py-2 rounded-lg bg-[#D4AF37]/[0.06] border border-[#D4AF37]/15">
              <p className="text-[10px] text-[#D4AF37]/60 uppercase tracking-wider mb-0.5">Prompt</p>
              <p className="text-xs text-[#D4AF37]/90 font-medium">{promptName}</p>
            </div>
          )}

          {/* Editable Prompt */}
          <div>
            <label className="block text-xs text-white/40 mb-1.5">Prompt Text</label>
            <textarea
              value={editablePrompt}
              onChange={(e) => setEditablePrompt(e.target.value)}
              rows={4}
              disabled={isGenerating}
              className="w-full px-3 py-2.5 rounded-xl bg-white/[0.03] border border-white/[0.08] text-sm text-white/80 placeholder-white/20 focus:outline-none focus:border-[#D4AF37]/30 resize-none disabled:opacity-50"
              placeholder="Enter your video prompt..."
            />
          </div>

          {/* Settings Grid */}
          <div className="grid grid-cols-3 gap-3">
            {/* Duration */}
            <div>
              <label className="block text-[10px] text-white/40 uppercase tracking-wider mb-1.5">Duration</label>
              <div className="flex gap-1.5">
                {['5', '10'].map(d => (
                  <button
                    key={d}
                    onClick={() => setDuration(d)}
                    disabled={isGenerating}
                    className={`flex-1 py-2 rounded-lg text-xs font-medium transition-all ${
                      duration === d
                        ? 'bg-[#D4AF37]/20 text-[#D4AF37] border border-[#D4AF37]/30'
                        : 'bg-white/[0.03] text-white/40 border border-white/[0.06] hover:bg-white/[0.06]'
                    } disabled:opacity-50`}
                  >
                    {d}s
                  </button>
                ))}
              </div>
            </div>

            {/* Aspect Ratio */}
            <div>
              <label className="block text-[10px] text-white/40 uppercase tracking-wider mb-1.5">Ratio</label>
              <select
                value={aspectRatio}
                onChange={(e) => setAspectRatio(e.target.value)}
                disabled={isGenerating}
                className="w-full py-2 px-2 rounded-lg text-xs bg-white/[0.03] border border-white/[0.06] text-white/70 focus:outline-none focus:border-[#D4AF37]/30 disabled:opacity-50"
              >
                <option value="9:16">9:16</option>
                <option value="16:9">16:9</option>
                <option value="1:1">1:1</option>
              </select>
            </div>

            {/* Resolution */}
            <div>
              <label className="block text-[10px] text-white/40 uppercase tracking-wider mb-1.5">Quality</label>
              <select
                value={resolution}
                onChange={(e) => setResolution(e.target.value)}
                disabled={isGenerating}
                className="w-full py-2 px-2 rounded-lg text-xs bg-white/[0.03] border border-white/[0.06] text-white/70 focus:outline-none focus:border-[#D4AF37]/30 disabled:opacity-50"
              >
                <option value="480p">480p</option>
                <option value="720p">720p</option>
                <option value="1080p">1080p</option>
              </select>
            </div>
          </div>

          {/* Progress Bar */}
          {isGenerating && (
            <div className="space-y-2">
              <div className="w-full h-3 rounded-full bg-white/[0.06] overflow-hidden">
                <div
                  className="h-full rounded-full transition-all duration-1000 ease-out"
                  style={{
                    width: `${Math.min(progress, 100)}%`,
                    background: 'linear-gradient(90deg, #D4AF37, #F5D76E)',
                  }}
                />
              </div>
              <div className="flex items-center justify-between">
                <p className="text-[11px] text-white/40">{statusMessage}</p>
                <p className="text-[11px] text-[#D4AF37] font-mono">{Math.round(progress)}%</p>
              </div>
            </div>
          )}

          {/* Video Preview */}
          {videoUrl && (
            <div className="space-y-3">
              <div className="rounded-xl overflow-hidden border border-[#D4AF37]/20 bg-black">
                <video
                  src={videoUrl}
                  controls
                  className="w-full"
                  style={{ maxHeight: '300px' }}
                />
              </div>
              <button
                onClick={handleDownload}
                className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 hover:bg-emerald-500/30 transition-colors text-sm font-medium"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                Download Video
              </button>
            </div>
          )}

          {/* Generate Button */}
          {!videoUrl && (
            <button
              onClick={handleGenerate}
              disabled={isGenerating || !editablePrompt.trim()}
              className={`w-full flex items-center justify-center gap-2 py-3.5 rounded-xl text-sm font-semibold transition-all ${
                isGenerating
                  ? 'bg-[#D4AF37]/10 text-[#D4AF37]/50 border border-[#D4AF37]/15 cursor-wait'
                  : 'bg-gradient-to-r from-[#D4AF37]/20 to-[#D4AF37]/10 text-[#D4AF37] border border-[#D4AF37]/30 hover:from-[#D4AF37]/30 hover:to-[#D4AF37]/20 active:scale-[0.98]'
              } disabled:opacity-40`}
            >
              {isGenerating ? (
                <>
                  <div className="w-4 h-4 border-2 border-[#D4AF37]/30 border-t-[#D4AF37] rounded-full animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                  </svg>
                  Generate Video (Grok)
                </>
              )}
            </button>
          )}

          {/* Generate Another */}
          {videoUrl && (
            <button
              onClick={() => {
                setVideoUrl(null);
                setProgress(0);
                setStatusMessage('');
              }}
              className="w-full py-2.5 rounded-xl text-xs text-white/40 border border-white/[0.06] hover:bg-white/[0.03] transition-colors"
            >
              Generate Another Video
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
